import { expect, test } from '@playwright/test'

test('responsive storefront and complete shopping flow', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Less noise. More feeling.' })).toBeVisible()
  await expect(page.locator('.model-container canvas')).toBeVisible()
  await page.waitForTimeout(1500)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-hero.png` })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: 'Chalk finish', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Chalk finish', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Meet Forma' }).click()
  await expect(page.getByRole('dialog')).toContainText('Chalk')
  await page.getByRole('button', { name: 'Increase Forma Chalk quantity' }).click()
  await expect(page.locator('.cart-total')).toContainText('$698')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Open shopping bag, 2 items' }).click()
  await expect(page.locator('.cart-total')).toContainText('$698')
  await page.getByRole('button', { name: 'Continue to demo checkout' }).click()
  await page.getByLabel('Name', { exact: true }).fill('Alex Listener')
  await page.getByLabel('Email', { exact: true }).fill('alex@example.com')
  await page.getByRole('button', { name: 'Place demo order' }).click()
  await expect(page.getByRole('heading', { name: 'Your demo order is complete.' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep listening' }).click()
  await page.getByRole('group', { name: 'Filter products' }).getByRole('button', { name: 'Earbuds' }).click()
  await expect(page.locator('.product-card')).toHaveCount(1)
  await expect(page.locator('.product-card h3')).toHaveText('Air')
  await page.getByRole('button', { name: 'View Air details' }).click()
  await page.getByRole('button', { name: 'Select Graphite' }).click()
  await page.getByRole('button', { name: 'Add to bag — $179' }).click()
  await expect(page.getByRole('dialog')).toContainText('Graphite')
  await page.getByRole('button', { name: 'Decrease Air Graphite quantity' }).click()
  await expect(page.getByRole('dialog')).toContainText('A little room for good sound.')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Search products', exact: true }).click()
  await page.getByRole('textbox', { name: 'Search products' }).fill('room')
  await expect(page.locator('.search-results > button')).toHaveCount(1)
  await page.locator('.search-results > button').click()
  await expect(page.getByRole('dialog')).toContainText('Good sound belongs everywhere.')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('group', { name: 'Filter products' }).getByRole('button', { name: 'All products' }).click()
  await page.locator('#collection').scrollIntoViewIfNeeded()
  await page.screenshot({ path: `test-results/${testInfo.project.name}-collection.png` })
  await page.locator('#experience').scrollIntoViewIfNeeded()
  await page.waitForTimeout(700)
  await page.screenshot({ path: `test-results/${testInfo.project.name}-story.png` })
  expect(errors).toEqual([])
})

test('reduced motion, keyboard dialogs, and invalid saved bags', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => localStorage.setItem('aure-bag', '[{"productId":"invalid","finish":"nope","quantity":-3}]'))
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Open shopping bag, 0 items' })).toBeVisible()
  await page.getByRole('button', { name: 'Search products', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Search products' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Search products', exact: true })).toBeFocused()
  if (testInfo.project.name === 'mobile') {
    await page.getByRole('button', { name: 'Toggle navigation' }).click()
    await page.getByRole('navigation', { name: 'Mobile navigation' }).getByRole('button', { name: 'Speakers' }).click()
    await expect(page.locator('.product-card')).toHaveCount(1)
    await expect(page.locator('.product-card h3')).toHaveText('Room')
  }
})
